### PR TITLE
Remove unused explicit dependencies

### PR DESCRIPTION
**Pull request by Turbo87**
All of these dependencies don't seem to be used anywhere 🤔

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
execa, etc, is needed for the integration tests :)

**Comment by Turbo87** [comment]
is it though... https://github.com/ember-codemods/ember-no-implicit-this-codemod/blob/594b92671ba0f65121f492fa1c4831754ee31274/test/run-test.ts#L4 😅 

but indeed, it looks like `common-tags` is still used.

**Comment by Turbo87** [comment]
ah, now I know what I did wrong... I only searched in `.js` file and didn't see the `.ts` files. 🤦‍♂

**Comment by NullVoxPopuli** [comment]
thank you!

**Pull request merged**
