### PR TITLE
Fix "data-*" attributes that were incorrectly prefixed with `this`

### LINKED ISSUE #48: 'data-test-' attributes are incorrectly prefixed with 'this' for curly bracket components
`data-test-` attributes are prefixed with `this` for curly bracket invoked components. Example diff:

```
-{{#paper-card data-test-job-profile-status as |card|}}
+{{#paper-card this.data-test-job-profile-status as |card|}}
```

The same attributes are handled properly for angle bracket invoked components.

I suppose I could run https://github.com/ember-codemods/ember-angle-brackets-codemod first. If that is the expectation then perhaps adding a note to the readme would be called for.

### PR DESCRIPTION
**Pull request by suchitadoshi1987**
Fixes #48

### CODE REVIEW

**Comment by rwjblue** [comment]
Hmm, I don't think we can assume that all `data-*` paths are not supposed to be `this` paths. 🤔

**Comment by suchitadoshi1987** [comment]
hmmm... wondering what would be the potential use-cases where `data-*` paths would not be attributes

**Comment by Turbo87** [comment]
I tend to agree with @rwjblue. This should be a configurable option. Though ideally we'd finally retire that pattern of positional `data-test` arguments. Inventing that was a bad idea in the first place... sorry 😞

Guess it's time to write a codemod to finally remove them 🤔

**Comment by suchitadoshi1987** [comment]
Agreed, like @Turbo87 pointed out, https://github.com/simplabs/ember-test-selectors-params-codemod would solve this issue. Closing this PR in favor of that.

**Pull request closed without merging**
