### PR TITLE
Prepare for ember-codemods-telemetry-helper package (use unified telemetry)

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Things to consider:
 - blocked by: https://github.com/ember-codemods/ember-codemods-telemetry-helpers/pull/1
 - https://github.com/ember-codemods/ember-no-implicit-this-codemod/pull/10/files (this PR adds local getters to the telemetry data -- this may not be needed by default if we assume everything get's `this` appended, but then we may mistakenly append `this` to arguments that have yet to adopt `@sigils`

### CODE REVIEW

**Comment by patocallaghan** [comment]
Any reason we shouldn't bump the the telemetry helpers package to 0.3.0 and merge this? That means then I can update my ES5 getters PR to use the telemetry-helpers instead.

**Comment by NullVoxPopuli** [comment]
Yeah, you could upgrade that in this pr

**Comment by patocallaghan** [comment]
I'm happy to push an update to this branch now if you're preoccupied?

**Comment by NullVoxPopuli** [comment]
yeah, go for it -- it's a tiny change :)

**Comment by patocallaghan** [comment]
I tried push to your branch but `ERROR: Permission to NullVoxPopuli/ember-no-implicit-this-codemod.git denied to patocallaghan.` 😬

**Comment by NullVoxPopuli** [comment]
Oh my, I thought I was commenting on a different PR, AND that this was already done :(


one sec

**Comment by patocallaghan** [comment]
ha thanks. I'll update to 0.3.0 in my getters PR then 👍

**Pull request merged**
