### PR TITLE
Support Modifiers

### LINKED ISSUE #42: Render modifiers prefixed with `this.`
I've used the `didInsert` modifier from `@ember/render-modifiers` in some templates and they are getting replaced with `this.didInsert`.

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Resolves #42

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
>  we should not propagate the idea that there are separate namespaces in handlebars files

what do you mean by this / how does this PR have that idea?

> We should assume there is a single unified list of available "invokable" things

I almost did that approach, the same way helpers and computeds are done right now, but found that the telemetry-helpers' default info collector doesn't do modifiers, so I came up with this approach.

> I don't think we need to track the first path expression within a modifier 

Tobias was saying the right thing to do would be to add some behavior to glimmer/syntax so that Path nodes can know what they are / have consumers of the visitor pattern not have to do what's being done in this codemod with enter/exit :man_shrugging: 
once that exists, I'm happy to delete code. :D

**Comment by rwjblue** [comment]
> found that the telemetry-helpers' default info collector doesn't do modifiers

We should fix it!

**Comment by rwjblue** [comment]
> Tobias was saying the right thing to do would be to add some behavior to glimmer/syntax so that Path nodes can know what they are / have consumers of the visitor pattern not have to do what's being done in this codemod with enter/exit 🤷‍♂

Ya, totally agree. I think that work would be great, but I don't think we need that for this _specific_ PR.

**Comment by NullVoxPopuli** [comment]
This passes locally, so maybe the failure is cache related?

**Comment by NullVoxPopuli** [comment]
@tylerturdenpants any chance you could take a gander at this? I'm confused why it seems like the test running on 3.13 doesn't match my machine -- so, I wonder if maybe my machine is somehow broken to the point of "working", and the broken state in CI is correct.

**Comment by tylerturdenpants** [comment]
Ya. I’ll take a look at it today. Going to work on a few telemetry related things.

**Comment by Turbo87** [comment]
I guess we can close this now, since #62 should've added support for modifiers 🎉

**Pull request closed without merging**
